import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, writeFile, mkdir, cp, unlink } from 'node:fs/promises';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { createHash } from 'node:crypto';
import { createCanvas, loadImage } from '@napi-rs/canvas';
import { configuration, root } from '../tools/studio/config.mjs';
import { startHost } from '../tools/studio/host.mjs';
import { editObject, jsonSpans } from '../tools/studio/json-edit.mjs';
import { CodexBridge } from '../tools/studio/codex.mjs';
import { selectionBounds, alignSelection, distributeSelection, gridSelection, snapMove } from '../studio/geometry.js';

test('editor geometry: edge/center guides, equal gaps, grid, axis lock and unequal element sizes',()=>{
  const n=(id,x,y,w=10,h=10,index=0)=>({id,index,rect:{x,y,w,h},props:{offset:[x,y]}});
  const a=n('a',0,0),b=n('b',30,0,20),c=n('c',80,0);
  assert.deepEqual(selectionBounds([a,b,c]),{x:0,y:0,w:90,h:10});
  assert.deepEqual(alignSelection([b],'centerX',{x:0,y:0,w:100,h:100})[0].patch.offset,[40,0]);
  assert.deepEqual(alignSelection([a,b,c],'bottom').map(e=>e.patch.offset),[[0,0],[30,0],[80,0]]);
  assert.deepEqual(distributeSelection([c,a,b],'x').map(e=>e.patch.offset),[[0,0],[35,0],[80,0]]);
  assert.throws(()=>distributeSelection([a,n('b',1,0),n('c',2,0)],'x'),/겹칩니다/);
  assert.deepEqual(gridSelection([a,b,c],2,8).map(e=>e.patch.offset),[[0,0],[28,0],[0,18]]);
  assert.throws(()=>gridSelection([a,b],0,8),/열 수/);
  const edge=snapMove({x:10,y:10,w:10,h:10},17,0,{peers:[n('peer',30,50)],grid:8,threshold:4});
  assert.equal(edge.dx,20,'smart alignment precedes a coarser grid');assert.equal(edge.guides[0].axis,'x');
  const spaced=snapMove({x:65,y:0,w:10,h:10},-6,0,{peers:[a,n('peer',30,0)],grid:0,threshold:2});
  assert.equal(spaced.dx,-5);assert.equal(spaced.guides.find(g=>g.gap!==undefined).gap,20);
  const left=snapMove({x:-35,y:0,w:10,h:10},6,0,{peers:[a,n('peer',30,0)],grid:0,threshold:2});
  assert.equal(left.guides.find(g=>g.gap!==undefined).to-left.guides.find(g=>g.gap!==undefined).from,20);
  assert.deepEqual(snapMove(a.rect,5,7,{smart:false,grid:0}),{dx:5,dy:7,guides:[]});
  assert.deepEqual(snapMove(a.rect,5,7,{smart:false,grid:8,axis:'x'}),{dx:8,dy:0,guides:[]});
  assert.equal(snapMove(a.rect,100,100,{peers:[b],grid:0,threshold:2}).guides.length,0);
  assert.throws(()=>alignSelection([{...a,props:{offset:['$x',0]}}],'left',b.rect),/동적 위치/);
});

test('JSONC patch preserves comments, escaped keys, trailing commas and unrelated content',()=>{
  const text='\uFEFF{\n// retained\n"a/b": {"size": [20, 10], /* sizing */ "text": "old", // keep\n}, "untouched": 1\n}';
  const updated=editObject(text,'/a~1b',{size:[24,12],offset:[3,4]});
  assert.match(updated,/\/\/ retained/);assert.match(updated,/\/\* sizing \*\//);assert.match(updated,/\/\/ keep/);assert.match(updated,/"untouched": 1/);
  assert.equal(jsonSpans(updated).kind,'{');
  assert.throws(()=>jsonSpans('{"a":1,"a":2}'),/duplicate/);
});

test('real Studio: source provenance, visual edits, undo, conflict, images, shared context, HTTP boundaries',{timeout:120000},async t=>{
  const config=await configuration();
  const dir=join(process.env.MCBEKIT_TEST_ROOT || join(root,'workspace/test-studio'),randomUUID());await mkdir(dir,{recursive:true});
  const rpRoot=join(dir,'rp');await cp(join(root,'examples/studio-rp'),rpRoot,{recursive:true});
  const host=await startHost({...config,port:0,runtime:join(dir,'runtime'),bridgeRoot:join(dir,'native')});t.after(()=>host.close());
  const s=host.session;
  const first=await s.open({rpRoot});assert.equal(first.status,'ready',first.error);assert.equal(s.editor.screens.length,1);
  const workerPid = s.worker.pid;
  const composite = createCanvas(...s.project.viewport), compositeCtx = composite.getContext('2d');
  compositeCtx.imageSmoothingEnabled = false;
  for (const sprite of s.editor.layers) { const b=sprite.bounds; compositeCtx.drawImage(await loadImage(Buffer.from(sprite.data.split(',')[1],'base64')),b.x,b.y,b.w,b.h); }
  assert.equal(createHash('sha256').update(await composite.encode('png')).digest('hex'),first.report.hash,'editor layers must composite to the exact engine preview');
  let node=s.editor.nodes.find(n=>n.id==='progress');assert.ok(node.source);assert.equal(node.source.pointer,'/screen/controls/4/progress');
  const original=await s.readSource('ui/live_demo.json'), initialHash=first.report.hash;
  await s.select({key:node.key});assert.equal(s.context().selection.id,'progress');
  await s.edit({key:node.key,expectedRevision:s.editorRevision,expectedHash:node.source.sha256,patch:{size:[80,12],offset:[9,35]}});
  const savedRevision=s.editorRevision;
  await new Promise(resolve=>setTimeout(resolve,350));
  assert.equal(s.revision,savedRevision,'a GUI save must not schedule a second watcher render');
  assert.equal(s.worker.pid,workerPid,'edits must reuse the renderer worker');
  assert.notEqual(s.state.report.hash,initialHash);assert.deepEqual(s.editor.nodes.find(n=>n.id==='progress').props.offset,[9,35]);
  await assert.rejects(s.edit({key:node.key,expectedRevision:s.editorRevision,expectedHash:original.sha256,patch:{alpha:.5}}),/SOURCE_CONFLICT/);
  await s.history({direction:'undo'});assert.equal((await s.readSource(original.path)).text,original.text);assert.equal(s.state.report.hash,initialHash);
  await s.history({direction:'redo'});assert.notEqual(s.state.report.hash,initialHash);
  const group=s.editor.nodes.filter(n=>['title','progress'].includes(n.id));
  await s.select({key:group[0].key,keys:group.map(n=>n.key)});assert.equal(s.context().selectionCount,2);assert.equal(s.context().selectionGroup.length,2);
  const beforeBatch=await s.readSource(original.path),historyCount=s.undoStack.length;
  const edits=group.map((n,i)=>({key:n.key,expectedHash:n.source.sha256,patch:{offset:[i*20,20]}}));
  await assert.rejects(s.batchEdit({expectedRevision:s.editorRevision,edits:edits.map((e,i)=>({...e,expectedHash:i?'stale':e.expectedHash}))}),/SOURCE_CONFLICT/);
  assert.equal((await s.readSource(original.path)).text,beforeBatch.text,'failed batches must never partially write');
  await s.batchEdit({expectedRevision:s.editorRevision,edits});assert.equal(s.undoStack.length,historyCount+1);
  assert.deepEqual(s.editor.nodes.find(n=>n.id==='progress').props.offset,[20,20]);
  await s.history({direction:'undo'});assert.equal((await s.readSource(original.path)).text,beforeBatch.text);
  const commented=beforeBatch.text.replace('"progress":{','"progress":{/* clone comment */"custom_extra":{"keep":"value"},');
  await s.writeSource({path:original.path,text:commented,expectedHash:beforeBatch.sha256});await s.render();
  let duplicateNode=s.editor.nodes.find(n=>n.id==='progress');
  await writeFile(join(rpRoot,'ir.yaml'),'version: 1\n');
  await assert.rejects(s.duplicate({key:duplicateNode.key,expectedRevision:s.editorRevision,expectedHash:duplicateNode.source.sha256}),/IR_OWNER/);
  await assert.rejects(s.batchEdit({expectedRevision:s.editorRevision,edits:[{key:duplicateNode.key,expectedHash:duplicateNode.source.sha256,patch:{offset:[3,4]}}]}),/IR_OWNER/);
  assert.equal((await s.readSource(original.path)).text,commented);await unlink(join(rpRoot,'ir.yaml'));
  const copied=await s.duplicate({key:duplicateNode.key,expectedRevision:s.editorRevision,expectedHash:duplicateNode.source.sha256});
  const clone=s.editor.nodes.find(n=>n.id===copied.id);assert.deepEqual(clone.props.offset,duplicateNode.props.offset.map(v=>v+8));assert.equal(clone.props.texture,duplicateNode.props.texture);
  const clonedText=(await s.readSource(original.path)).text;assert.equal((clonedText.match(/clone comment/g)||[]).length,2);assert.equal((clonedText.match(/"custom_extra"/g)||[]).length,2);
  await s.history({direction:'undo'});assert.equal((await s.readSource(original.path)).text,commented);
  await s.select({key:null});await s.render();assert.equal(s.context().selectionCount,0);assert.equal(s.context().selection,undefined);
  await assert.rejects(s.writeSource({path:original.path,text:'{"broken":',expectedHash:(await s.readSource(original.path)).sha256}));
  await assert.rejects(s.readSource('../outside.json'));
  const pixel=await readFile(join(rpRoot,'textures/ui/live_pixel.png'));
  await assert.rejects(s.importImage({name:'broken.png',data:Buffer.from('not-png').toString('base64')}),/PNG/);
  const uploaded=await s.importImage({name:'../../sprite.png',data:pixel.toString('base64')});assert.match(uploaded.texture,/^textures\/studio\//);
  await s.render();node=s.editor.nodes[0];
  await s.add({key:node.key,expectedRevision:s.editorRevision,expectedHash:node.source.sha256,type:'image',texture:uploaded.texture});
  assert.ok(s.editor.nodes.some(n=>n.props.texture===uploaded.texture));
  const latest=await s.readSource(original.path);await writeFile(join(rpRoot,original.path),latest.text+'\n// external edit\n');
  await assert.rejects(s.history({direction:'undo'}),/SOURCE_CONFLICT/);
  const externalDeadline=Date.now()+5000;
  while((s.editorRevision===savedRevision||s.state.stale||s.editor.nodes[0].source.sha256!==createHash('sha256').update(latest.text+'\n// external edit\n').digest('hex'))&&Date.now()<externalDeadline)await new Promise(resolve=>setTimeout(resolve,40));
  assert.equal(s.editor.nodes[0].source.sha256,createHash('sha256').update(latest.text+'\n// external edit\n').digest('hex'),'external writes must still refresh the shared source evidence');
  await s.acceptFrame({data:pixel.toString('base64'),source:'test window'});assert.equal(s.context().gameFrame.source,'test window');
  s.clearFrame();assert.equal(s.context().gameFrame,null);
  const preview=await readFile(s.state.report.outputPath);
  await s.acceptBrowserFrame({data:preview.toString('base64'),revision:s.state.renderedRevision,fontMode:'approximate'});assert.equal(s.context().previewFontMode,'approximate-system-font');
  await assert.rejects(s.acceptBrowserFrame({data:pixel.toString('base64'),revision:0}),/PREVIEW_CONFLICT/);
  await assert.rejects(s.acceptBrowserFrame({data:pixel.toString('base64'),revision:s.state.renderedRevision}),/dimensions/);
  const sharp = createCanvas(s.project.viewport[0]*2,s.project.viewport[1]*2);
  sharp.getContext('2d').drawImage(await loadImage(preview),0,0,sharp.width,sharp.height);
  await s.acceptBrowserFrame({data:(await sharp.encode('png')).toString('base64'),revision:s.state.renderedRevision,captureScale:2,fontMode:'approximate'});
  assert.equal(s.context().previewCaptureScale,2);
  await assert.rejects(s.acceptBrowserFrame({data:preview.toString('base64'),revision:s.state.renderedRevision,captureScale:2}),/dimensions/);
  const changedCatalog = await s.readSource(original.path);
  await s.writeSource({path:original.path,text:editObject(changedCatalog.text,'',{extra_screen:{type:'panel',size:[32,32]}}),expectedHash:changedCatalog.sha256});
  await s.render();assert.ok(s.editor.screens.some(screen=>screen.control==='live_demo.extra_screen'));
  await writeFile(join(rpRoot,'ir.yaml'),'schema_version: 1\n');node=s.editor.nodes[0];
  await assert.rejects(s.edit({key:node.key,expectedRevision:s.editorRevision,expectedHash:node.source.sha256,patch:{offset:[1,1]}}),/IR_OWNER/);
  const request=async(path,headers={})=>fetch(host.connection.url+path,{method:path.startsWith('/api/')?'POST':'GET',headers});
  assert.equal((await request('/api/status')).status,401);
  assert.equal((await request('/api/status',{Authorization:'Bearer '+host.connection.token,Origin:'https://example.com'})).status,403);
  const html=await request('/');assert.match(html.headers.get('content-security-policy'),/script-src 'self'/);
  assert.equal((await request('/app.js')).status,200);assert.equal((await request('/style.css')).status,200);assert.equal((await request('/geometry.js')).status,200);
  const ctx=await request('/api/studio_context',{Authorization:'Bearer '+host.connection.token});assert.equal((await ctx.json()).runtimeVerified,false);
  const restored=await startHost({...config,port:0,runtime:join(dir,'runtime'),bridgeRoot:join(dir,'native')});t.after(()=>restored.close());
  assert.equal(restored.session.project.control,s.project.control,'restart must restore the last screen');
  assert.equal(restored.session.state.status,'ready');
});

test('Codex streams actual protocol items, exposes approvals, rejects unsupported requests, and handles completion',()=>{
  const sent=[],session={config:{},render:async()=>{}};
  const bridge=new CodexBridge(session);bridge.threadId='thread';bridge.child={stdin:{writable:true,write:line=>sent.push(JSON.parse(line))}};
  bridge.receive({method:'item/agentMessage/delta',params:{threadId:'thread',itemId:'a',delta:'안녕'}});
  bridge.receive({method:'item/agentMessage/delta',params:{threadId:'thread',itemId:'a',delta:'하세요'}});
  assert.equal(bridge.messages[0].text,'안녕하세요');
  bridge.receive({id:5,method:'item/commandExecution/requestApproval',params:{command:'node verify.mjs'}});
  assert.equal(bridge.status().requests.length,1);assert.equal(sent.length,0);
  bridge.reply({id:5,decision:'decline'});assert.equal(sent[0].result.decision,'decline');
  bridge.receive({id:6,method:'unsupported/test',params:{}});assert.equal(sent[1].error.code,-32601);
  bridge.receive({id:7,method:'mcpServer/elicitation/request',params:{mode:'form',requestedSchema:{properties:{confirm:{type:'boolean'}}}}});
  assert.equal(sent.length,2);bridge.reply({id:7,decision:'accept',content:{confirm:true}});assert.deepEqual(sent[2].result,{action:'accept',content:{confirm:true}});
  bridge.busy=true;bridge.receive({method:'turn/completed',params:{threadId:'thread',turn:{id:'turn',status:'completed'}}});assert.equal(bridge.busy,false);
});
test('Codex feedback steers the exact active turn with fresh selection context',async()=>{
  const bridge=new CodexBridge({config:{},project:{},context:()=>({stale:false,selection:{id:'title'}})});
  bridge.busy=true;bridge.threadId='thread';bridge.turnId='active';let called;
  bridge.rpc=async(method,params)=>{called={method,params};return {turnId:'active'};};
  await bridge.message({text:'제목을 크게',includePreview:false});
  assert.equal(called.method,'turn/steer');assert.equal(called.params.expectedTurnId,'active');assert.equal(called.params.input[0].text,'제목을 크게');
  assert.equal(bridge.busy,true);assert.equal(bridge.messages.at(-1).role,'user');
});
